// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies_List.Models;

namespace Movies_List.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20220125230257_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Movies_List.Models.NewMovieForm", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Response");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action",
                            Director = "Anthony Russo",
                            Edited = false,
                            LentTo = "",
                            Notes = "Super good, but there were a few things it was missing",
                            Rating = "PG-13",
                            Title = "Avengers End Game",
                            Year = "2019"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Action",
                            Director = "Jon Watts",
                            Edited = false,
                            LentTo = "Jake Pingree",
                            Notes = "Super good",
                            Rating = "PG-13",
                            Title = "Spider-Man No Way Home",
                            Year = "2021"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Comedy",
                            Director = "Jaume Collet-Serra",
                            Edited = true,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Jungle Cruise",
                            Year = "2021"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
